---
title: "FINAL Lung PhenoSurv Figures"
author: "S. Grant"
date: "2025-05-27"
output: html_document
---

(A) concordance index of PhenoSurv and previously published models with pathway and genomic data

```{r}
data <- read.csv("~//Documents//Survival VAE//Lung & Brain Final Model CIs.csv")

data <- subset(data, Cancer_Type == "Brain")

data$Class[data$Model == "VAE (Weighted Surv)"] <- "PhenoSurv"
data.rm <- subset(data, Model == "VAE")
data <- dplyr::setdiff(data, data.rm)

mycolors <- colorRampPalette(c("#D81B60", "#1E88E5", "#FFC107"))(5)
data$Class <- factor(data$Class, levels = c("RSF (Genomic)", "RSF (Pathway Scores)", "DeepSurv (Genomic)",
                                            "DeepSurv (Pathway Scores)", "PhenoSurv"))


tcga_cis_combined <- ggplot(subset(data, Dataset == "TCGA"), aes(fill = Class, y = CI, x = Class)) +
  geom_boxplot(position=position_dodge(1)) +
  theme_classic() +
  scale_fill_manual(values = mycolors) +
    xlab("Model") +
  ylab("Concordance Index") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank()) 
  #stat_compare_means(comparisons = list(c("PhenoSurv", "DeepSurv (Pathway Scores)"),
  #                                      c("PhenoSurv", "DeepSurv (Genomic)"),
  #                                      c("PhenoSurv", "RSF (Pathway Scores)"),
  #                                      c("PhenoSurv", "RSF (Genomic)")), hide.ns = T, label = "p.signif") # saved 500 x 300 svg

msk_cis_combined <- ggplot(subset(data, Dataset == "MSK"), aes(fill = Class, y = CI, x = Class)) +
  geom_boxplot(position=position_dodge(1)) +
  theme_classic() +
  scale_fill_manual(values = mycolors) +
    xlab("Model") +
  ylab("Concordance Index") +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank(), axis.title.x = element_blank()) +
  #ylim(0,1)+
  stat_compare_means(comparisons = list(c("PhenoSurv", "DeepSurv (Genomic)")), hide.ns = T, label = "p.signif") # saved 500 x 300 svg

ggpubr::ggarrange(msk_cis_combined, tcga_cis_combined, common.legend = TRUE, ncol = 1, nrow = 2,
                  legend = "right")
```
Overall mean values (TCGA)

```{r}
print(mean(subset(data, Class == "RSF (Genomic)" & Dataset == "TCGA")$CI))
print(mean(subset(data, Class == "RSF (Pathway Scores)" & Dataset == "TCGA")$CI))
print(mean(subset(data, Class == "DeepSurv (Genomic)" & Dataset == "TCGA")$CI))
print(mean(subset(data, Class == "DeepSurv (Pathway Scores)" & Dataset == "TCGA")$CI))
print(mean(subset(data, Class == "PhenoSurv" & Dataset == "TCGA")$CI))
```

Overall mean values (MSK)

```{r}
print(mean(subset(data, Class == "RSF (Genomic)" & Dataset == "MSK")$CI))
print(mean(subset(data, Class == "RSF (Pathway Scores)" & Dataset == "MSK")$CI))
print(mean(subset(data, Class == "DeepSurv (Genomic)" & Dataset == "MSK")$CI))
print(mean(subset(data, Class == "DeepSurv (Pathway Scores)" & Dataset == "MSK")$CI))
print(mean(subset(data, Class == "PhenoSurv" & Dataset == "MSK")$CI))
```



(B) hazard ratio of phenotype-based latent dimensions from trained PhenoSurv models

```{r}
pc <- rbind(read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//brain_train_data_MSK_FINAL.csv'))

Scaler <- caret::preProcess(pc[,1:11], rangeBounds = c(-1,1),method = "range")
pc_scaled = predict(Scaler,pc[,1:11])
pc <- cbind(pc_scaled, pc[,12:13])

fit1_pc <- coxph(Surv(TIME, STATUS) ~ DNA_REPAIR, data = pc)
fit2_pc <- coxph(Surv(TIME, STATUS) ~ EVADE_GROWTH_SUPPRESSORS, data = pc)
fit3_pc <- coxph(Surv(TIME, STATUS) ~ HORMONE_SIGNALING, data = pc)
fit4_pc <- coxph(Surv(TIME, STATUS) ~ IMMUNE, data = pc)
fit5_pc <- coxph(Surv(TIME, STATUS) ~ INFLAMMATION, data = pc)
fit6_pc <- coxph(Surv(TIME, STATUS) ~ PLASTICITY, data = pc)
fit7_pc <- coxph(Surv(TIME, STATUS) ~ PROLIFERATION, data = pc)
fit8_pc <- coxph(Surv(TIME, STATUS) ~ METASTASIS, data = pc)
fit9_pc <- coxph(Surv(TIME, STATUS) ~ METABOLISM, data = pc)
fit10_pc <- coxph(Surv(TIME, STATUS) ~ RESIST_CELL_DEATH, data = pc)
fit11_pc <- coxph(Surv(TIME, STATUS) ~ VASCULATOR, data = pc)


df_hr <- data.frame("Phenotype" = rep(c("DNA REPAIR", "EVADE GROWTH SUPPRESSORS", "HORMONE SIGNALING", "IMUNE", "INFLAMMATION", "PLASTICITY",
                                    "PROLIFERATION", "METASTASIS", "METABOLISM", "RESIST CELL DEATH", "VASCULATOR"),1),
                    "Dataset" = c(rep("MSK", 11)),
                    "COEF" = c(0.6937, -0.06379, 0.6461, 1.0157, 0.3061, 1.0578, -0.9845, 0.862, 0.1612, -0.6614, 0.5999),
                    "SE" = c(0.1814, 0.25102, 0.2021, 0.1762, 0.2536, 0.2097, 0.197, 0.2281, 0.2257, 0.1566, 0.2789))

df_hr$COEF <- abs(df_hr$COEF)

df_hr$Start <- df_hr$COEF - df_hr$SE
df_hr$End <- df_hr$COEF + df_hr$SE



df <- df_hr

df$Phenotype[df$Phenotype == "VASCULATOR"] <- "VASCULATURE"


df$Phenotype[df_hr$Phenotype == "IMUNE"] <- "IMMUNE"


rank <- df
rank <- rank[order(-rank$COEF),]
rank <- rank$Phenotype

df$Phenotype <- factor(df$Phenotype, levels = rev(rank))

msk_plot <- ggplot(df, aes(y = Phenotype, x = COEF)) +
              geom_point(position = position_dodge(width=0.75), color = "#1E88E5") +
              geom_vline(xintercept = 0, linetype = "dashed") +
              geom_segment(aes(x = Start, xend = End, y = Phenotype), position = position_dodge(width=0.75), color = "#1E88E5") +
              theme_classic() +
  xlab("Impact") +
  ylab(NULL)
msk_plot

```




(C) mean SHAP values of top 5 pathways from each phenotype

```{r}
mycolors <- colorRampPalette(c("#D81B60", "#1E88E5", "#FFC107"))(11)
top = 5
shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_dna_repair_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df1 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df1 <- df1[order(-df1$Mean_SHAP),]
df1_pc <- df1[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_growth_suppressor_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df2 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df2 <- df2[order(-df2$Mean_SHAP),]
df2_pc <- df2[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_hormone_signaling_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df3 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df3 <- df3[order(-df3$Mean_SHAP),]
df3_pc <- df3[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_immune_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df4 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df4 <- df4[order(-df4$Mean_SHAP),]
df4_pc <- df4[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_inflammation_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df5 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df5 <- df5[order(-df5$Mean_SHAP),]
df5_pc <- df5[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_metabolism_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df6 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df6 <- df6[order(-df6$Mean_SHAP),]
df6_pc <- df6[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_metastasis_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df7 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df7 <- df7[order(-df7$Mean_SHAP),]
df7_pc <- df7[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_plasticity_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df8 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df8 <- df8[order(-df8$Mean_SHAP),]
df8_pc <- df8[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_proliferation_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df9 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df9 <- df9[order(-df9$Mean_SHAP),]
df9_pc <- df9[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_resist_cell_death_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df10 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df10 <- df10[order(-df10$Mean_SHAP),]
df10_pc <- df10[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_vasculator_PC_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df11 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df11 <- df11[order(-df11$Mean_SHAP),]
df11_pc <- df11[1:top,]

df1_pc$Group = "DNA REPAIR"
df2_pc$Group = "EVADE GROWTH SUPPRESSORS"
df3_pc$Group = "HORMONE SIGNALING"
df4_pc$Group = "IMMUNE"
df5_pc$Group = "INFLAMMATION"
df6_pc$Group = "METABOLISM"
df7_pc$Group = "METASTASIS"
df8_pc$Group = "PLASTICITY"
df9_pc$Group = "PROLIFERATION"
df10_pc$Group = "RESIST CELL DEATH"
df11_pc$Group = "VASCULATURE"

df_pheno_pc <- rbind(df1_pc, df2_pc, df3_pc, df4_pc, df5_pc, df6_pc, df7_pc, df8_pc, df9_pc, df10_pc, df11_pc)

df_pheno_pc$Group <- as.factor(df_pheno_pc$Group)
# Set a number of 'empty bar' to add at the end of each group
empty_bar <- 1
to_add <- data.frame( matrix(NA, empty_bar*nlevels(df_pheno_pc$Group), ncol(df_pheno_pc)) )
colnames(to_add) <- colnames(df_pheno_pc)
to_add$Group <- rep(levels(df_pheno_pc$Group), each=empty_bar)
df_pheno_pc <- rbind(df_pheno_pc, to_add)
df_pheno_pc <- df_pheno_pc %>% arrange(Group)
df_pheno_pc$id <- seq(1, nrow(df_pheno_pc))

# Get the name and the y position of each label
label_data <- df_pheno_pc
number_of_bar <- nrow(label_data)
angle <- 90 - 360 * (label_data$id-0.5) /number_of_bar     # I substract 0.5 because the letter must have the angle of the center of the bars. Not extreme right(1) or extreme left (0)
label_data$hjust <- ifelse( angle < -90, 1, 0)
label_data$angle <- ifelse(angle < -90, angle+180, angle)


# prepare a data frame for base lines
base_data <- df_pheno_pc %>% 
  group_by(Group) %>% 
  dplyr::summarize(start=min(id), end=max(id) - empty_bar) %>% 
  rowwise() %>% 
  mutate(title=mean(c(start, end)))

# prepare a data frame for grid (scales)
grid_data <- base_data
grid_data$end <- grid_data$end[ c( nrow(grid_data), 1:nrow(grid_data)-1)] + 1
grid_data$start <- grid_data$start - 1
grid_data <- grid_data[-1,]

p_pc_hr <- ggplot(df_pheno_pc, aes(x=as.factor(id), y=Mean_SHAP, fill=Group)) +  
  geom_bar(aes(x=as.factor(id), y=Mean_SHAP, fill=Group), stat="identity") +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm")
  ) +
  coord_polar() +
  scale_fill_manual(values = mycolors) +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_segment(data=base_data, aes(x = start, y = -0.0125, xend = end, yend = -0.0125), colour = mycolors, alpha=1, size=2 , inherit.aes = FALSE ) 

p_pc_hr

```


```{r}
ggsave("~//Documents//Survival VAE//Figures//v3//p_pc_brain_v2.svg", plot = p_pc_hr, bg = "transparent", width = 8, height = 6)
```



(D) SHAP values of top pathways shared by both TCGA and MSK models

```{r}
####### HR POS

library(tidyverse)
library(paletteer)
library(ggplot2)



top = 10
shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_dna_repair_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df1 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df1 <- df1[order(-df1$Mean_SHAP),]
df1_pc <- df1[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_growth_suppressor_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df2 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df2 <- df2[order(-df2$Mean_SHAP),]
df2_pc <- df2[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_hormone_signaling_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df3 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df3 <- df3[order(-df3$Mean_SHAP),]
df3_pc <- df3[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_immune_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df4 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df4 <- df4[order(-df4$Mean_SHAP),]
df4_pc <- df4[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_inflammation_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df5 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df5 <- df5[order(-df5$Mean_SHAP),]
df5_pc <- df5[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_metabolism_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df6 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df6 <- df6[order(-df6$Mean_SHAP),]
df6_pc <- df6[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_metastasis_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df7 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df7 <- df7[order(-df7$Mean_SHAP),]
df7_pc <- df7[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_plasticity_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df8 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df8 <- df8[order(-df8$Mean_SHAP),]
df8_pc <- df8[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_proliferation_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df9 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df9 <- df9[order(-df9$Mean_SHAP),]
df9_pc <- df9[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_resist_cell_death_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df10 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df10 <- df10[order(-df10$Mean_SHAP),]
df10_pc <- df10[1:top,]

shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_vasculator_MSK_FINAL_brain.csv')
pathways <- shap_values$Pathway
shap_values <- shap_values[,-ncol(shap_values)]
shap_values <- apply(shap_values, 2, abs)
shap_mean <- apply(shap_values, 1, mean)

df11 <- data.frame("Pathway" = pathways, "Mean_SHAP" = shap_mean)
df11 <- df11[order(-df11$Mean_SHAP),]
df11_pc <- df11[1:top,]

df1_pc$Group = "DNA REPAIR"
df2_pc$Group = "EVADE GROWTH SUPPRESSORS"
df3_pc$Group = "HORMONE SIGNALING"
df4_pc$Group = "IMMUNE"
df5_pc$Group = "INFLAMMATION"
df6_pc$Group = "METABOLISM"
df7_pc$Group = "METASTASIS"
df8_pc$Group = "PLASTICITY"
df9_pc$Group = "PROLIFERATION"
df10_pc$Group = "RESIST CELL DEATH"
df11_pc$Group = "VASCULATURE"

df_pheno_pc <- rbind(df1_pc, df2_pc, df3_pc, df4_pc, df5_pc, df6_pc, df7_pc, df8_pc, df9_pc, df10_pc, df11_pc)
```



```{r}
tcga_hormone_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_hormone_signaling_MSK_FINAL_brain.csv')
tcga_hormone_shap_values <- subset(tcga_hormone_shap_values, Pathway %in% subset(df_pheno_pc, Group == "HORMONE SIGNALING")$Pathway)
tcga_growth_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_growth_suppressor_MSK_FINAL_brain.csv')
tcga_growth_shap_values <- subset(tcga_growth_shap_values, Pathway %in% subset(df_pheno_pc, Group == "EVADE GROWTH SUPPRESSORS")$Pathway)
tcga_proliferation_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_proliferation_MSK_FINAL_brain.csv')
tcga_proliferation_shap_values <- subset(tcga_proliferation_shap_values, Pathway %in% subset(df_pheno_pc, Group == "PROLIFERATION")$Pathway)
tcga_resist_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_resist_cell_death_MSK_FINAL_brain.csv')
tcga_resist_shap_values <- subset(tcga_resist_shap_values, Pathway %in% subset(df_pheno_pc, Group == "RESIST CELL DEATH")$Pathway)
tcga_immune_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_immune_MSK_FINAL_brain.csv')
tcga_immune_shap_values <- subset(tcga_immune_shap_values, Pathway %in% subset(df_pheno_pc, Group == "IMMUNE")$Pathway)
tcga_vasculature_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_vasculator_MSK_FINAL_brain.csv')
tcga_vasculature_shap_values <- subset(tcga_vasculature_shap_values, Pathway %in% subset(df_pheno_pc, Group == "VASCULATURE")$Pathway)
tcga_metastasis_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_metastasis_MSK_FINAL_brain.csv')
tcga_metastasis_shap_values <- subset(tcga_metastasis_shap_values, Pathway %in% subset(df_pheno_pc, Group == "METASTASIS")$Pathway)
tcga_dna_repair_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_dna_repair_MSK_FINAL_brain.csv')
tcga_dna_repair_shap_values <- subset(tcga_dna_repair_shap_values, Pathway %in% subset(df_pheno_pc, Group == "DNA REPAIR")$Pathway)
tcga_inflammation_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_inflammation_MSK_FINAL_brain.csv')
tcga_inflammation_shap_values <- subset(tcga_inflammation_shap_values, Pathway %in% subset(df_pheno_pc, Group == "INFLAMMATION")$Pathway)
tcga_plasticity_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_plasticity_MSK_FINAL_brain.csv')
tcga_plasticity_shap_values <- subset(tcga_plasticity_shap_values, Pathway %in% subset(df_pheno_pc, Group == "PLASTICITY")$Pathway)
tcga_metabolism_shap_values <- read.csv('~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_shapvalues_metabolism_MSK_FINAL_brain.csv')
tcga_metabolism_shap_values <- subset(tcga_metabolism_shap_values, Pathway %in% subset(df_pheno_pc, Group == "METABOLISM")$Pathway)

tcga_shap_values <- rbind(tcga_hormone_shap_values, tcga_dna_repair_shap_values, tcga_growth_shap_values, tcga_immune_shap_values,
                          tcga_inflammation_shap_values, tcga_metabolism_shap_values, tcga_metastasis_shap_values, 
                          tcga_plasticity_shap_values, tcga_proliferation_shap_values, tcga_resist_shap_values, tcga_vasculature_shap_values)

```

```{r}
df_pheno_pc <- df_pheno_pc[order(-df_pheno_pc$Mean_SHAP),]
top20 <- df_pheno_pc[1:15,]

tcga_shap_values <- subset(tcga_shap_values, Pathway %in% top20$Pathway)

```
```{r}
library(ggbeeswarm)
test_cols <- read.csv("~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_values_MSK_FINAL_brain_pathwaynames.csv")
test_vals <- read.csv("~//Documents//Survival VAE//FINAL PHENOSURV//v2//test_values_MSK_FINAL_brain.csv")

colnames(test_vals) <- colnames(test_cols)

test_vals <- test_vals[,unique(tcga_shap_values$Pathway)]
```

```{r}
# rearrange data
df2 <- data.frame()
for (i in 1:nrow(tcga_shap_values)){
  path <- tcga_shap_values$Pathway[i]
  shap_vals <- tcga_shap_values[i,-ncol(tcga_shap_values)]
  real_vals <- test_vals[,path]
  rows <- data.frame("SHAP" = as.numeric(shap_vals), "Pathway" = path, "Vals" = real_vals)
  df2 <- rbind(df2, rows)
}
```

```{r}
library(ggnewscale)
df2$Pathway <- factor(df2$Pathway, levels = rev(unique(top20$Pathway)))
hr_bs_plot <- ggplot(df2, aes(x = SHAP, y = Pathway, fill = Vals, color = Vals)) +
  geom_quasirandom() +
  theme_classic()+
  scale_color_gradient(low = "#1E88E5", high = "#D81B60") +
  scale_fill_gradient(low = "#1E88E5", high = "#D81B60")
hr_bs_plot
```

```{r}
ggsave("~//Documents//Survival VAE//Figures//v3//brain shap plot msk.svg", plot = hr_bs_plot, bg = "transparent", width = 10, height = 6)
```

